"""
Business objective
------------------
Create presentation-ready plots that fully support Task 1: Data Exploration &
Quality Assessment for the LPBF quality prediction case study.

The figures explain:
- what data we have
- whether the data is trustworthy
- whether there are missing values, outliers, inconsistencies, or imbalance
- whether distributions look physically realistic
- whether the dataset preserves expected LPBF physics
- whether quality labels contain useful predictive signal
- which features appear related to quality
- which process-physics relationships should be investigated
- which assumptions are being made
- why prediction timing determines which features are allowed
- why the recommended MVP should focus on in-build prediction

Coding objective
----------------
Generate business-facing figures into reports/figures/business using consistent
logic, consistent colors, clear conclusions, and reusable plotting functions.
"""

from pathlib import Path
import textwrap

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from lpbf_quality.data.challenge_analysis import run_challenge_analysis
from lpbf_quality.config.settings import (
    CATEGORICAL_FEATURES,
    FIGURES_DIR,
    POST_BUILD_FEATURES,
    PROCESS_FEATURES,
    QUALITY_ORDER,
    TARGET_COLUMN,
)


BUSINESS_FIGURES_DIR = FIGURES_DIR / "business"

FEATURE_GROUP_COLORS = {
    "Material / categorical": "#2ca02c",
    "Process / monitoring": "#1f77b4",
    "Post-build diagnostic": "#ff7f0e",
    "Other": "#7f7f7f",
}

SEVERITY_COLORS = {
    "LOW": "#2ca02c",
    "MEDIUM": "#ff7f0e",
    "HIGH": "#d62728",
}


def _save_plot(output_path: Path) -> None:
    """
    Business objective
    ------------------
    Save figures consistently so they can be reused directly in the final
    PowerPoint.

    Coding objective
    ----------------
    Create parent folders, save the plot at presentation quality, and close the
    figure to avoid memory buildup.

    Important implementation note
    -----------------------------
    We intentionally do not call plt.tight_layout() here because several
    presentation figures use fig.text() captions below the axes. Calling
    tight_layout globally can move axes on top of those captions. Individual
    plotting functions control their own spacing with subplots_adjust().
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=180, bbox_inches="tight", pad_inches=0.25)
    plt.close()

def _wrap_text(text: str, width: int = 42) -> str:
    """
    Business objective
    ------------------
    Keep long labels and recommendations readable inside business-facing plots.

    Coding objective
    ----------------
    Wrap long strings into multiple lines for matplotlib annotations.
    """

    return "\n".join(textwrap.wrap(str(text), width=width))


def _classify_feature_group(feature: str) -> str:
    """
    Business objective
    ------------------
    Make feature importance easier to interpret by separating deployable
    operational signals from post-build diagnostic measurements.

    Coding objective
    ----------------
    Return a standardized feature group label used for plotting.
    """

    if feature in POST_BUILD_FEATURES:
        return "Post-build diagnostic"

    if feature in PROCESS_FEATURES:
        return "Process / monitoring"

    if feature in CATEGORICAL_FEATURES:
        return "Material / categorical"

    return "Other"


def _read_challenge_report(
    eda_output_dir: str | Path,
    file_name: str,
) -> pd.DataFrame:
    """
    Business objective
    ------------------
    Reuse the independent challenge reports already generated by run_eda.py
    instead of silently trusting the original EDA conclusions.

    Coding objective
    ----------------
    Read a challenge CSV from reports/eda/challenge and return an empty
    DataFrame if it is not available.
    """

    path = Path(eda_output_dir) / "challenge" / file_name

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


def _format_metric(value: object, digits: int = 3) -> str:
    """
    Business objective
    ------------------
    Keep numeric evidence readable in presentation tables.

    Coding objective
    ----------------
    Format floats consistently while leaving non-numeric values unchanged.
    """

    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return str(value)


def plot_dataset_overview(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Provide a simple executive overview of the dataset before discussing models.

    Coding objective
    ----------------
    Create a table-style figure summarizing rows, columns, feature groups, and
    the prediction target.
    """

    output_dir = Path(output_dir)

    numeric_count = len(df.select_dtypes(include="number").columns)
    categorical_count = len(df.select_dtypes(exclude="number").columns)

    rows = [
        ["Rows", f"{len(df):,}"],
        ["Columns", f"{df.shape[1]}"],
        ["Target", TARGET_COLUMN],
        ["Target classes", ", ".join(QUALITY_ORDER)],
        ["Numeric columns", str(numeric_count)],
        ["Categorical columns", str(categorical_count)],
        ["Material / categorical features", str(len(CATEGORICAL_FEATURES))],
        ["Process / monitoring features", str(len(PROCESS_FEATURES))],
        ["Post-build diagnostic features", str(len(POST_BUILD_FEATURES))],
    ]

    fig, ax = plt.subplots(figsize=(12, 5.8))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Dataset Overview",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "The dataset contains material, process, monitoring, inspection, "
            "and quality outcome information."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Item", "Value"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.45)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "01_dataset_overview.png")


def plot_quality_class_distribution(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Show whether the target classes are sufficiently represented for supervised
    learning.

    Coding objective
    ----------------
    Generate a target distribution chart with class percentages and imbalance
    interpretation.
    """

    output_dir = Path(output_dir)

    counts = df[TARGET_COLUMN].value_counts()
    min_count = counts.min()
    max_count = counts.max()
    imbalance_ratio = max_count / min_count if min_count > 0 else float("inf")

    plt.figure(figsize=(10, 5))
    ax = sns.countplot(data=df, x=TARGET_COLUMN, order=QUALITY_ORDER)

    total = len(df)

    for container in ax.containers:
        ax.bar_label(
            container,
            labels=[
                f"{int(v.get_height())}\n{v.get_height() / total:.1%}"
                for v in container
            ],
            fontsize=9,
        )

    ax.text(
        0.03,
        0.92,
        (
            "Key finding\n"
            f"Class imbalance ratio = {imbalance_ratio:.2f}\n"
            "Acceptable for baseline modeling\n"
            "Track recall/F1 by class"
        ),
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=10,
        bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="black"),
    )

    plt.title("Quality Class Distribution")
    plt.xlabel("Quality Class")
    plt.ylabel("Number of Samples")

    _save_plot(output_dir / "02_quality_class_distribution.png")


def plot_data_quality_audit(
    eda_output_dir: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Summarize missing values, duplicates, schema issues, invalid ranges, and
    constant features in one reviewable quality gate slide.

    Coding objective
    ----------------
    Read validation reports and create a pass/warn/fail summary table.
    """

    eda_output_dir = Path(eda_output_dir)
    output_dir = Path(output_dir)

    def count_status(file_name: str, status: str) -> int:
        path = eda_output_dir / file_name

        if not path.exists():
            return 0

        report = pd.read_csv(path)

        if "status" not in report.columns:
            return 0

        return int((report["status"] == status).sum())

    missing_path = eda_output_dir / "missing_values.csv"
    duplicates_path = eda_output_dir / "duplicates.csv"
    physical_path = eda_output_dir / "physical_ranges.csv"

    missing_count = 0
    if missing_path.exists():
        missing = pd.read_csv(missing_path)
        if "missing_count" in missing.columns:
            missing_count = int(missing["missing_count"].sum())

    duplicate_count = 0
    if duplicates_path.exists():
        duplicates = pd.read_csv(duplicates_path)
        if "duplicate_count" in duplicates.columns:
            duplicate_count = int(duplicates["duplicate_count"].sum())

    invalid_range_count = 0
    if physical_path.exists():
        physical = pd.read_csv(physical_path)
        if "invalid_count" in physical.columns:
            invalid_range_count = int(physical["invalid_count"].sum())

    constant_warnings = count_status("constant_features.csv", "WARN")

    rows = [
        ["Schema validation", "PASS", "Expected columns available"],
        ["Missing values", "PASS" if missing_count == 0 else "WARN", str(missing_count)],
        ["Duplicate rows", "PASS" if duplicate_count == 0 else "WARN", str(duplicate_count)],
        [
            "Invalid physical ranges",
            "PASS" if invalid_range_count == 0 else "WARN",
            str(invalid_range_count),
        ],
        [
            "Constant / near-constant features",
            "PASS" if constant_warnings == 0 else "WARN",
            str(constant_warnings),
        ],
    ]

    fig, ax = plt.subplots(figsize=(12, 5.8))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Data Quality Audit",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        "Mandatory production checks found no blocking data quality issue.",
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Check", "Status", "Details"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.5)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    ax.text(
        0,
        -0.08,
        (
            "Engineering interpretation: the dataset is clean enough for modeling, "
            "but production risks still need review."
        ),
        fontsize=10,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    _save_plot(output_dir / "03_data_quality_audit.png")


def plot_feature_distributions_physics(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Show the distribution of key LPBF process, monitoring, and inspection
    variables so reviewers can see whether the data looks physically realistic.

    Coding objective
    ----------------
    Create compact histograms for representative physics-related features.
    """

    output_dir = Path(output_dir)

    selected_features = [
        "Energy_Density_J_mm3",
        "Thermal_Gradient",
        "Melt_Pool_Temp_C",
        "Melt_Pool_Depth_um",
        "Relative_Density_percent",
        "Porosity_percent",
        "Microhardness_HV",
        "Defect_Count",
    ]

    selected_features = [col for col in selected_features if col in df.columns]

    if not selected_features:
        return

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for ax, feature in zip(axes, selected_features):
        sns.histplot(df[feature], kde=True, ax=ax)
        ax.set_title(feature)
        ax.set_xlabel("")
        ax.set_ylabel("Count")

    for ax in axes[len(selected_features):]:
        ax.axis("off")

    fig.suptitle("Feature Distributions for Key LPBF Variables", fontsize=15)

    fig.text(
        0.5,
        0.035,
        (
            "Engineering interpretation: bounded, smooth distributions suggest "
            "controlled operating windows or pre-cleaned/synthetic data."
        ),
        ha="center",
        fontsize=10,
    )

    fig.subplots_adjust(bottom=0.18, top=0.88, hspace=0.42, wspace=0.25)
    _save_plot(output_dir / "04_feature_distributions_physics.png")


def plot_outlier_assessment(
    eda_output_dir: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
    top_n: int = 12,
) -> None:
    """
    Business objective
    ------------------
    Show whether numeric features contain unusual values and interpret the
    absence of outliers from a manufacturing data perspective.

    Coding objective
    ----------------
    Read outliers.csv and plot the top features by IQR outlier percentage.
    """

    eda_output_dir = Path(eda_output_dir)
    output_dir = Path(output_dir)

    path = eda_output_dir / "outliers.csv"

    if not path.exists():
        return

    outliers = pd.read_csv(path)

    if outliers.empty or "outlier_percent" not in outliers.columns:
        return

    plot_df = outliers.copy()

    # Sample_ID is an identifier, not a physical process feature.
    plot_df = plot_df[plot_df["feature"] != "Sample_ID"]

    plot_df = plot_df.sort_values("outlier_percent", ascending=False).head(top_n)
    plot_df = plot_df.sort_values("outlier_percent", ascending=True)

    plt.figure(figsize=(11, 6))
    ax = sns.barplot(
        data=plot_df,
        x="outlier_percent",
        y="feature",
    )

    max_value = plot_df["outlier_percent"].max()

    if max_value == 0:
        ax.set_xlim(0, 1)
    else:
        ax.set_xlim(0, max_value * 1.2)

    ax.text(
        0.98,
        0.08,
        (
            "Engineering interpretation:\n"
            "No IQR outliers detected.\n\n"
            "This is unusual for raw production data\n"
            "and suggests controlled, pre-cleaned,\n"
            "or synthetic operating windows.\n\n"
            "No automatic outlier removal applied."
        ),
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=9,
        bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="black"),
    )

    plt.title("Outlier Assessment by Numeric Feature")
    plt.xlabel("IQR Outlier Share (%)")
    plt.ylabel("Feature")

    _save_plot(output_dir / "05_outlier_assessment.png")


def plot_physics_correlation_heatmap(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Show relationships between process physics variables and quality-related
    inspection outcomes.

    Coding objective
    ----------------
    Create a targeted correlation heatmap using LPBF-relevant numeric features.
    """

    output_dir = Path(output_dir)

    physics_features = [
        "Laser_Power_W",
        "Scan_Speed_mm_s",
        "Hatch_Spacing_mm",
        "Layer_Thickness_um",
        "Energy_Density_J_mm3",
        "Melt_Pool_Depth_um",
        "Melt_Pool_Temp_C",
        "Cooling_Rate_K_s",
        "Thermal_Gradient",
        "Relative_Density_percent",
        "Porosity_percent",
        "Microhardness_HV",
        "Defect_Count",
    ]

    physics_features = [col for col in physics_features if col in df.columns]

    if len(physics_features) < 2:
        return

    corr = df[physics_features].corr()

    plt.figure(figsize=(13, 10))
    sns.heatmap(
        corr,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        center=0,
        linewidths=0.4,
        cbar_kws={"label": "Correlation"},
    )

    plt.title("Physics-Oriented Correlation Map")

    _save_plot(output_dir / "06_physics_correlation_heatmap.png")


def plot_process_window_power_speed(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Show whether poor/moderate quality risk concentrates in specific LPBF
    power-speed operating windows without overplotting thousands of points.

    Coding objective
    ----------------
    Bin scan speed and laser power into a 2D process-window grid, calculate the
    Poor + Moderate rate in each bin, and visualize the result as a heatmap.
    """

    output_dir = Path(output_dir)

    required = {"Laser_Power_W", "Scan_Speed_mm_s", TARGET_COLUMN}

    if not required.issubset(df.columns):
        return

    risk_classes = {"Poor", "Moderate"}
    work = df[list(required)].dropna().copy()

    if work.empty:
        return

    work["scan_speed_bin"] = pd.cut(
        work["Scan_Speed_mm_s"],
        bins=6,
        include_lowest=True,
    )
    work["laser_power_bin"] = pd.cut(
        work["Laser_Power_W"],
        bins=6,
        include_lowest=True,
    )
    work["is_risk_class"] = work[TARGET_COLUMN].isin(risk_classes).astype(int)

    grouped = (
        work.groupby(["laser_power_bin", "scan_speed_bin"], observed=True)
        .agg(
            samples=(TARGET_COLUMN, "size"),
            risk_rate_percent=("is_risk_class", lambda x: x.mean() * 100),
        )
        .reset_index()
    )

    # Convert interval labels into short readable axis labels.
    grouped["scan_label"] = grouped["scan_speed_bin"].apply(
        lambda interval: f"{interval.left:.0f}-{interval.right:.0f}"
    )
    grouped["power_label"] = grouped["laser_power_bin"].apply(
        lambda interval: f"{interval.left:.0f}-{interval.right:.0f}"
    )

    heatmap_data = grouped.pivot(
        index="power_label",
        columns="scan_label",
        values="risk_rate_percent",
    )

    sample_data = grouped.pivot(
        index="power_label",
        columns="scan_label",
        values="samples",
    )

    # Preserve physical order: low power at bottom, high power at top.
    heatmap_data = heatmap_data.iloc[::-1]
    sample_data = sample_data.iloc[::-1]

    annotation = heatmap_data.copy().astype(object)
    for row_label in heatmap_data.index:
        for col_label in heatmap_data.columns:
            rate = heatmap_data.loc[row_label, col_label]
            count = sample_data.loc[row_label, col_label]
            annotation.loc[row_label, col_label] = (
                "" if pd.isna(rate) else f"{rate:.1f}%\nn={int(count)}"
            )

    fig, ax = plt.subplots(figsize=(12.5, 7.2))

    sns.heatmap(
        heatmap_data,
        annot=annotation,
        fmt="",
        cmap="YlOrRd",
        vmin=0,
        vmax=100,
        linewidths=0.5,
        linecolor="white",
        cbar_kws={"label": "Poor + Moderate rate (%)"},
        ax=ax,
    )

    ax.set_title("LPBF Process Window Risk: Laser Power vs Scan Speed", fontsize=14)
    ax.set_xlabel("Scan Speed Bin (mm/s)")
    ax.set_ylabel("Laser Power Bin (W)")
    ax.tick_params(axis="x", rotation=25)
    ax.tick_params(axis="y", rotation=0)

    ax.text(
        0.01,
        -0.18,
        (
            "Method: scan speed and laser power are binned into a 6×6 process "
            "window. Each cell shows Poor + Moderate rate and sample count. "
            "Interpretation: no strong high-risk pocket is visible; risk appears "
            "broadly distributed across the window."
        ),
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        wrap=True,
    )

    fig.subplots_adjust(bottom=0.24, top=0.88, left=0.12, right=0.96)
    _save_plot(output_dir / "07_process_window_power_speed.png")


def plot_energy_density_quality_physics(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Test whether energy-density regions show different quality risk without
    relying on unreadable point clouds.

    Coding objective
    ----------------
    Bin Energy_Density_J_mm3, calculate Poor + Moderate rate per bin, and show
    sample counts so reviewers can judge whether a visible trend is supported.
    """

    output_dir = Path(output_dir)

    required = {"Energy_Density_J_mm3", TARGET_COLUMN}

    if not required.issubset(df.columns):
        return

    risk_classes = {"Poor", "Moderate"}
    work = df[list(required)].dropna().copy()

    if work.empty:
        return

    work["energy_density_bin"] = pd.cut(
        work["Energy_Density_J_mm3"],
        bins=8,
        include_lowest=True,
    )
    work["is_risk_class"] = work[TARGET_COLUMN].isin(risk_classes).astype(int)

    summary = (
        work.groupby("energy_density_bin", observed=True)
        .agg(
            samples=(TARGET_COLUMN, "size"),
            risk_rate_percent=("is_risk_class", lambda x: x.mean() * 100),
        )
        .reset_index()
    )

    summary["energy_label"] = summary["energy_density_bin"].apply(
        lambda interval: f"{interval.left:.0f}-{interval.right:.0f}"
    )

    overall_risk_rate = work["is_risk_class"].mean() * 100

    fig, ax = plt.subplots(figsize=(12.5, 6.8))

    sns.barplot(
        data=summary,
        x="energy_label",
        y="risk_rate_percent",
        ax=ax,
    )

    ax.axhline(
        overall_risk_rate,
        linestyle="--",
        linewidth=1.4,
        color="black",
        label=f"Overall Poor + Moderate rate: {overall_risk_rate:.1f}%",
    )

    for index, row in summary.iterrows():
        ax.text(
            index,
            row["risk_rate_percent"] + 0.8,
            f"{row['risk_rate_percent']:.1f}%\nn={int(row['samples'])}",
            ha="center",
            va="bottom",
            fontsize=8,
        )

    ax.set_ylim(0, max(60, summary["risk_rate_percent"].max() + 10))
    ax.set_title("Energy Density Quality Risk by Operating Bin", fontsize=14)
    ax.set_xlabel("Energy Density Bin (J/mm³)")
    ax.set_ylabel("Poor + Moderate Rate (%)")
    ax.tick_params(axis="x", rotation=25)
    ax.legend(loc="upper right")

    ax.text(
        0.01,
        -0.24,
        (
            "Method: energy density is binned into 8 operating ranges. Each bar "
            "shows the share of Poor + Moderate samples in that range. LPBF "
            "expectation: very low energy density can cause lack of fusion; very "
            "high energy density can cause instability/keyholing. Observation: "
            "risk stays close to the overall baseline, so this dataset does not "
            "show a strong energy-density quality trend."
        ),
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        wrap=True,
    )

    fig.subplots_adjust(bottom=0.30, top=0.88, left=0.10, right=0.96)
    _save_plot(output_dir / "08_energy_density_quality_physics.png")


def plot_physics_relationship_assumptions(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Document physics assumptions used to guide feature engineering and model
    interpretation.

    Coding objective
    ----------------
    Create a table-style figure summarizing expected LPBF relationships.
    """

    output_dir = Path(output_dir)

    rows = [
        [
            "Laser power / scan speed",
            "Controls energy input",
            "Use power-speed and energy-density features",
        ],
        [
            "Energy density",
            "Too low may cause lack of fusion; too high may cause instability",
            "Model nonlinear process window effects",
        ],
        [
            "Melt pool depth / temperature",
            "Reflects fusion behavior and thermal stability",
            "Useful for in-build prediction",
        ],
        [
            "Thermal gradient / cooling rate",
            "Influences residual stress and microstructure",
            "Useful monitoring features",
        ],
        [
            "Porosity / density / defect count",
            "Measure final build quality",
            "Use for diagnosis, not pre-inspection prediction",
        ],
    ]

    fig, ax = plt.subplots(figsize=(14, 6))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Physics-Based Interpretation of Feature Groups",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        "The EDA checks whether expected LPBF process relationships are visible in the data.",
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Relationship", "Physical meaning", "Modeling implication"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(8.8)
    table.scale(1, 1.6)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "10_physics_relationship_assumptions.png")


def plot_process_relationships_by_quality(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Show practical relationships between important LPBF process variables and
    Quality_Class.

    Coding objective
    ----------------
    Create a compact multi-panel boxplot figure for selected process features.
    """

    output_dir = Path(output_dir)

    selected_features = [
        "Energy_Density_J_mm3",
        "Thermal_Gradient",
        "Powder_Size_um",
        "Melt_Pool_Depth_um",
        "Melt_Pool_Temp_C",
        "Scan_Speed_mm_s",
    ]

    selected_features = [col for col in selected_features if col in df.columns]

    if not selected_features:
        return

    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()

    for ax, feature in zip(axes, selected_features):
        sns.boxplot(
            data=df,
            x=TARGET_COLUMN,
            y=feature,
            order=QUALITY_ORDER,
            ax=ax,
        )
        ax.set_title(feature)
        ax.set_xlabel("")
        ax.tick_params(axis="x", rotation=20)

    for ax in axes[len(selected_features):]:
        ax.axis("off")

    fig.suptitle("Process and Monitoring Features by Quality Class", fontsize=15)

    fig.text(
        0.5,
        0.055,
        (
            "Purpose: identify whether process parameters shift across quality classes. "
            "Similar distributions suggest weak marginal separation, so nonlinear "
            "interactions may be important."
        ),
        ha="center",
        fontsize=10,
    )

    fig.subplots_adjust(bottom=0.22, top=0.86, hspace=0.55, wspace=0.28)
    _save_plot(output_dir / "11_process_relationships_by_quality.png")


def plot_top_mutual_information_features(
    mutual_information_path: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
    top_n: int = 15,
) -> None:
    """
    Business objective
    ------------------
    Identify which variables appear most associated with Quality_Class before
    modeling, while making clear which ones are operationally available.

    Coding objective
    ----------------
    Read mutual_information.csv and create a ranked horizontal bar chart using
    consistent feature-group colors.
    """

    output_dir = Path(output_dir)
    mutual_information_path = Path(mutual_information_path)

    if not mutual_information_path.exists():
        return

    mi = pd.read_csv(mutual_information_path)

    if mi.empty or "mutual_information_score" not in mi.columns:
        return

    top_features = mi.head(top_n).copy()
    top_features["feature_group"] = top_features["feature"].apply(
        _classify_feature_group
    )
    top_features = top_features.sort_values(
        "mutual_information_score",
        ascending=True,
    )

    plt.figure(figsize=(11, 7.5))
    ax = sns.barplot(
        data=top_features,
        x="mutual_information_score",
        y="feature",
        hue="feature_group",
        dodge=False,
        palette=FEATURE_GROUP_COLORS,
    )

    ax.text(
        0.98,
        0.05,
        (
            "Important observation:\n"
            "Several highly informative features\n"
            "are post-build diagnostic measurements.\n\n"
            "Conclusion:\n"
            "Prediction timing must drive feature selection."
        ),
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=9,
        bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="black"),
    )

    plt.title(f"Top {top_n} Features Associated with Quality Class")
    plt.xlabel("Mutual Information Score")
    plt.ylabel("Feature")
    plt.legend(title="Feature Group")

    _save_plot(output_dir / "12_top_mutual_information_features.png")


def plot_actionable_categorical_summary(
    df: pd.DataFrame,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Summarize whether early business-actionable categorical choices have strong
    differences in quality risk.

    Coding objective
    ----------------
    Compute Poor + Moderate percentage for each categorical feature value and
    show the result as a concise table.
    """

    output_dir = Path(output_dir)

    risk_classes = {"Poor", "Moderate"}
    rows = []

    for feature in CATEGORICAL_FEATURES:
        if feature not in df.columns:
            continue

        grouped = df.groupby(feature)[TARGET_COLUMN]

        for category, values in grouped:
            count = len(values)
            risk_count = int(values.isin(risk_classes).sum())
            risk_rate = risk_count / count * 100 if count > 0 else 0

            rows.append(
                {
                    "Variable": feature,
                    "Category": str(category),
                    "Poor + Moderate Rate": f"{risk_rate:.1f}%",
                    "Samples": count,
                }
            )

    risk_df = pd.DataFrame(rows)

    if risk_df.empty:
        return

    risk_df["_risk_numeric"] = (
        risk_df["Poor + Moderate Rate"].str.replace("%", "").astype(float)
    )
    risk_df = risk_df.sort_values("_risk_numeric", ascending=False).drop(
        columns="_risk_numeric"
    )

    fig, ax = plt.subplots(figsize=(13, 5.8))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Actionable Categorical Variables",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "These variables are available before production decisions. "
            "Observed risk differences are modest, suggesting process variables "
            "may carry more signal."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=risk_df[
            ["Variable", "Category", "Poor + Moderate Rate", "Samples"]
        ].values,
        colLabels=["Variable", "Category", "Poor + Moderate Rate", "Samples"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(8.8)
    table.scale(1, 1.45)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    ax.text(
        0,
        -0.08,
        (
            "Conclusion: categorical planning variables alone are unlikely to "
            "explain quality; process and monitoring features are expected to "
            "be more useful."
        ),
        fontsize=10,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    _save_plot(output_dir / "13_actionable_categorical_summary.png")


def plot_prediction_timing_timeline(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain that prediction timing defines which features are available and
    therefore which features are valid.

    Coding objective
    ----------------
    Create a simple timeline diagram for the presentation.
    """

    output_dir = Path(output_dir)

    fig, ax = plt.subplots(figsize=(12.5, 4.8))
    ax.axis("off")

    stages = [
        (0.12, "Pre-build", "Material\nplanned settings", "Predict before build starts"),
        (0.39, "In-build", "Process + melt pool\nthermal monitoring", "Update risk during build"),
        (0.66, "Post-build", "Density, porosity\nstrength, defects", "Diagnose after inspection"),
        (0.90, "Decision logic", "Only use features\navailable at that time", "Avoid timing leakage"),
    ]

    for x, title, detail, note in stages:
        ax.text(
            x,
            0.68,
            title,
            ha="center",
            va="center",
            fontsize=11,
            fontweight="bold",
            bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="black"),
        )
        ax.text(x, 0.41, detail, ha="center", va="center", fontsize=10)
        ax.text(x, 0.18, note, ha="center", va="center", fontsize=9)

    for start, end in [
        ((0.20, 0.68), (0.31, 0.68)),
        ((0.47, 0.68), (0.58, 0.68)),
        ((0.74, 0.68), (0.82, 0.68)),
    ]:
        ax.annotate(
            "",
            xy=end,
            xytext=start,
            arrowprops=dict(arrowstyle="->", linewidth=1.6),
        )

    ax.text(
        0.02,
        0.02,
        (
            "Assumption: prediction timing is treated as a design choice because "
            "the task asks for production-oriented quality prediction."
        ),
        ha="left",
        va="bottom",
        fontsize=9,
    )

    plt.title("Prediction Timing Determines Which Features Are Allowed", fontsize=14)

    _save_plot(output_dir / "14_prediction_timing_timeline.png")


def plot_timing_sensitive_features_table(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Make timing leakage concrete by listing the exact post-build features.

    Coding objective
    ----------------
    Create a table-style figure showing timing-sensitive features.
    """

    output_dir = Path(output_dir)

    reasons = {
        "Relative_Density_percent": "Post-build density result",
        "Porosity_percent": "Post-build porosity result",
        "Microhardness_HV": "Post-build material test",
        "Surface_Roughness_Ra": "Post-build surface inspection",
        "Tensile_Strength_MPa": "Mechanical testing result",
        "Yield_Strength_MPa": "Mechanical testing result",
        "Elongation_percent": "Mechanical testing result",
        "Defect_Count": "Inspection result",
    }

    rows = [
        [feature, reasons.get(feature, "Post-build measurement")]
        for feature in POST_BUILD_FEATURES
    ]

    fig, ax = plt.subplots(figsize=(12, 5.5))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Timing-Sensitive Post-Build Features",
        fontsize=15,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "These features are valid for post-build diagnosis, but not for "
            "prediction before inspection."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Feature", "Timing dependency"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 1.45)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    ax.text(
        0,
        -0.08,
        f"Key finding: {len(POST_BUILD_FEATURES)} timing-sensitive post-build features identified.",
        fontsize=11,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    _save_plot(output_dir / "15_timing_sensitive_features_table.png")


def plot_preprocessing_strategy(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain what preprocessing is applied and why those choices are practical
    for industrial data.

    Coding objective
    ----------------
    Create a table-style figure documenting preprocessing decisions.
    """

    output_dir = Path(output_dir)

    rows = [
        ["Schema validation", "Detect changed or missing columns before modeling"],
        ["Missing value checks", "Prevent silent training failures"],
        ["Physical range checks", "Catch impossible machine or inspection values"],
        ["Outlier flagging", "Review extreme process windows instead of deleting automatically"],
        ["Categorical encoding", "Convert alloy, morphology, and scan strategy for ML models"],
        ["Scenario-specific feature selection", "Avoid timing leakage"],
        ["Stratified train/test split", "Preserve quality class proportions"],
        ["Class-specific metrics", "Evaluate Poor and Moderate detection, not accuracy only"],
    ]

    fig, ax = plt.subplots(figsize=(13, 6))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Preprocessing Strategy",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "Preprocessing choices are designed for reliability, traceability, "
            "and production use."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Step", "Engineering reason"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 1.45)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "16_preprocessing_strategy.png")


def plot_feature_engineering_strategy(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain how feature engineering connects statistics to LPBF process physics.

    Coding objective
    ----------------
    Create a table-style figure documenting feature engineering ideas.
    """

    output_dir = Path(output_dir)

    rows = [
        ["Energy density checks", "Validate / derive LPBF energy input behavior"],
        ["Power-speed relationships", "Capture interaction between laser power and scan speed"],
        ["Melt pool ratios", "Represent process stability and fusion behavior"],
        ["Thermal indicators", "Capture cooling and thermal gradient effects"],
        ["Oxygen / powder interactions", "Represent material condition effects"],
        ["Scenario feature views", "Create pre-build, in-build, and diagnostic datasets"],
    ]

    fig, ax = plt.subplots(figsize=(13, 5.8))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Feature Engineering Strategy",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "Engineering features are used to represent process physics, not only "
            "raw CSV columns."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Feature engineering idea", "Why it matters"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 1.45)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "17_feature_engineering_strategy.png")


def plot_prediction_scenarios_table(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain the possible prediction scenarios and recommended MVP.

    Coding objective
    ----------------
    Create a table-style figure summarizing prediction timing options.
    """

    output_dir = Path(output_dir)

    rows = [
        [
            "Pre-build",
            "Material + planned settings",
            "Risk screening before build starts",
            "Useful, but limited signal",
        ],
        [
            "In-build",
            "Material + process + monitoring",
            "Update risk during production",
            "Recommended MVP",
        ],
        [
            "Post-build",
            "All features including inspection",
            "Root-cause and diagnostic analysis",
            "Not a real-time prediction model",
        ],
    ]

    fig, ax = plt.subplots(figsize=(14, 5.5))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Prediction Scenarios and Recommended MVP",
        fontsize=15,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "Recommended MVP: in-build prediction using process and monitoring "
            "signals before final inspection."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Scenario", "Allowed features", "Business value", "Recommendation"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(8.7)
    table.scale(1, 1.6)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "18_prediction_scenarios_table.png")


def plot_risk_assessment_details(
    risk_assessment_path: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain production risks, their impact, and mitigation actions.

    Coding objective
    ----------------
    Read production_risk_assessment.csv and create a severity chart.
    """

    output_dir = Path(output_dir)
    risk_assessment_path = Path(risk_assessment_path)

    if not risk_assessment_path.exists():
        return

    risks = pd.read_csv(risk_assessment_path)

    if risks.empty:
        return

    severity_score = {"LOW": 1, "MEDIUM": 2, "HIGH": 3}

    impact_by_risk = {
        "Data leakage": "Artificially high offline accuracy",
        "Outliers / unusual process windows": "Possible weak robustness",
        "Class imbalance": "Risk of under-detecting poor builds",
        "Feature redundancy": "Harder model interpretation",
        "Machine/process drift": "Model performance may degrade over time",
    }

    risks["severity_score"] = risks["severity"].map(severity_score).fillna(0)
    risks["impact"] = risks["risk"].map(impact_by_risk).fillna(
        "Requires engineering review"
    )
    risks = risks.sort_values("severity_score", ascending=True)

    plt.figure(figsize=(15, 7.5))
    ax = sns.barplot(
        data=risks,
        y="risk",
        x="severity_score",
        hue="severity",
        palette=SEVERITY_COLORS,
    )

    ax.set_xlim(0, 5.8)
    ax.set_xticks([1, 2, 3])
    ax.set_xticklabels(["Low", "Medium", "High"])

    for i, row in risks.reset_index(drop=True).iterrows():
        ax.text(
            row["severity_score"] + 0.10,
            i,
            (
                f"Priority {len(risks) - i}: {row['severity']}\n"
                f"Impact: {row['impact']}\n"
                f"Action: {_wrap_text(row['recommended_action'], width=55)}"
            ),
            va="center",
            fontsize=8,
        )

    plt.title("Production Risk Assessment: Impact and Recommended Actions")
    plt.xlabel("Severity")
    plt.ylabel("")
    plt.legend(title="Severity")

    _save_plot(output_dir / "19_production_risk_assessment_details.png")


def plot_model_decision_tree_strategy(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Explain why different feature sets are prepared depending on prediction
    timing.

    Coding objective
    ----------------
    Create a simple decision-flow figure.
    """

    output_dir = Path(output_dir)

    fig, ax = plt.subplots(figsize=(13, 7))
    ax.axis("off")

    boxes = [
        (0.08, 0.70, "Question\nWhen is the prediction needed?"),
        (0.38, 0.84, "Operational prediction\nPre-build / in-build"),
        (0.38, 0.54, "Diagnostic analysis\nPost-build"),
        (0.72, 0.84, "Inputs\nFeatures available at prediction time"),
        (0.72, 0.54, "Inputs\nInspection and test results allowed"),
        (0.72, 0.24, "Final strategy\nCreate scenario-specific feature sets"),
    ]

    for x, y, text in boxes:
        ax.text(
            x,
            y,
            text,
            ha="center",
            va="center",
            fontsize=11,
            bbox=dict(boxstyle="round,pad=0.5", edgecolor="black", facecolor="white"),
        )

    for start, end in [
        ((0.18, 0.72), (0.29, 0.82)),
        ((0.18, 0.68), (0.29, 0.56)),
        ((0.49, 0.84), (0.62, 0.84)),
        ((0.49, 0.54), (0.62, 0.54)),
        ((0.72, 0.76), (0.72, 0.66)),
        ((0.72, 0.46), (0.72, 0.34)),
    ]:
        ax.annotate(
            "",
            xy=end,
            xytext=start,
            arrowprops=dict(arrowstyle="->", linewidth=1.5),
        )

    ax.text(
        0.06,
        0.23,
        (
            "Key point:\n"
            "A feature is not globally allowed or forbidden.\n"
            "It is allowed only if it exists at the prediction time.\n\n"
            "Therefore, data preparation must create separate\n"
            "pre-build, in-build, and diagnostic feature views."
        ),
        ha="left",
        va="center",
        fontsize=11,
        bbox=dict(boxstyle="round,pad=0.5", facecolor="white", edgecolor="black"),
    )

    plt.title("Modeling Strategy Driven by Prediction Timing", fontsize=14)

    _save_plot(output_dir / "20_model_decision_tree_strategy.png")


def plot_dataset_assumptions(
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Make dataset assumptions explicit so reviewers understand the limits of the
    analysis.

    Coding objective
    ----------------
    Create a table-style figure documenting assumptions and risks.
    """

    output_dir = Path(output_dir)

    rows = [
        [
            "Rows represent independent builds or samples",
            "No batch or build grouping information is provided",
        ],
        [
            "Quality_Class labels are treated as ground truth",
            "No alternative inspection labels are available",
        ],
        [
            "No IQR outliers detected",
            "Likely controlled/pre-cleaned/synthetic operating windows",
        ],
        [
            "Post-build inspection features are timing-sensitive",
            "They cannot be used before inspection without leakage",
        ],
        [
            "Future production resembles the dataset",
            "Must be monitored for machine, powder, and sensor drift",
        ],
    ]

    fig, ax = plt.subplots(figsize=(13, 5.8))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Dataset Assumptions and Practical Limits",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "These assumptions guide preprocessing, feature selection, and model "
            "risk discussion."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Assumption", "Reason / risk"],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 1.55)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    _save_plot(output_dir / "21_dataset_assumptions.png")

def plot_physics_consistency_challenge(
    df: pd.DataFrame,
    eda_output_dir: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Present the independent challenge layer that tested whether the clean
    dataset also behaves like realistic LPBF production data.

    Coding objective
    ----------------
    Read challenge reports generated by challenge_analysis.py, summarize the
    most important realism checks, and create one presentation-ready figure.
    """

    output_dir = Path(output_dir)
    eda_output_dir = Path(eda_output_dir)

    distribution_report = _read_challenge_report(
        eda_output_dir,
        "distribution_challenge.csv",
    )
    physics_report = _read_challenge_report(
        eda_output_dir,
        "physics_correlation_challenge.csv",
    )
    energy_report = _read_challenge_report(
        eda_output_dir,
        "energy_density_formula_challenge.csv",
    )
    separation_report = _read_challenge_report(
        eda_output_dir,
        "quality_separation_challenge.csv",
    )
    model_report = _read_challenge_report(
        eda_output_dir,
        "quick_model_predictability_challenge.csv",
    )
    leakage_report = _read_challenge_report(
        eda_output_dir,
        "leakage_challenge.csv",
    )

    # Fallback: if business plots are run directly without first running the
    # Level 3 challenge checks, generate the challenge CSV files now.
    if (
        distribution_report.empty
        and physics_report.empty
        and energy_report.empty
        and separation_report.empty
        and model_report.empty
        and leakage_report.empty
    ):
        reports = run_challenge_analysis(df, eda_output_dir / "challenge")
        distribution_report = reports.get("distribution_challenge", pd.DataFrame())
        physics_report = reports.get("physics_correlation_challenge", pd.DataFrame())
        energy_report = reports.get("energy_density_formula_challenge", pd.DataFrame())
        separation_report = reports.get("quality_separation_challenge", pd.DataFrame())
        model_report = reports.get("quick_model_predictability_challenge", pd.DataFrame())
        leakage_report = reports.get("leakage_challenge", pd.DataFrame())

    highly_uniform_count = "N/A"
    if not distribution_report.empty and "uniformity_score" in distribution_report:
        highly_uniform_count = int(
            (distribution_report["uniformity_score"] >= 0.95).sum()
        )

    weak_physics_result = "N/A"
    if not physics_report.empty and "absolute_correlation" in physics_report:
        weak_physics_count = int(
            (physics_report["absolute_correlation"] < 0.10).sum()
        )
        weak_physics_result = f"{weak_physics_count}/{len(physics_report)} weak"

    energy_result = "N/A"
    energy_interpretation = "Energy-density formula report not available"
    if (
        not energy_report.empty
        and "correlation_observed_vs_calculated" in energy_report
    ):
        energy_row = energy_report.iloc[0]
        energy_result = (
            "corr="
            f"{_format_metric(energy_row['correlation_observed_vs_calculated'], 3)}"
            ", MAPE="
            f"{_format_metric(energy_row.get('mean_absolute_percent_error'), 1)}%"
        )
        energy_interpretation = str(energy_row.get("interpretation", ""))

    weak_separation_result = "N/A"
    if (
        not separation_report.empty
        and "class_separation_signal" in separation_report
    ):
        weak_separation_count = int(
            (
                separation_report["class_separation_signal"]
                == "Weak / no clear class separation"
            ).sum()
        )
        weak_separation_result = (
            f"{weak_separation_count}/{len(separation_report)} weak"
        )

    model_result = "N/A"
    model_interpretation = "Quick model report not available"
    if not model_report.empty and "balanced_accuracy" in model_report:
        model_row = model_report.iloc[0]
        model_result = (
            "balanced acc="
            f"{_format_metric(model_row['balanced_accuracy'], 3)} "
            "(random="
            f"{_format_metric(model_row['random_chance_baseline'], 3)})"
        )
        model_interpretation = str(model_row.get("interpretation", ""))

    leakage_count = len(leakage_report)

    rows = [
        [
            "Distribution realism",
            f"{highly_uniform_count} highly uniform variables",
            "Suggests bounded, pre-cleaned, or synthetic data behavior",
        ],
        [
            "Energy-density formula",
            energy_result,
            _wrap_text(energy_interpretation, width=52),
        ],
        [
            "Expected physics correlations",
            weak_physics_result,
            "Expected LPBF relationships are not strongly visible",
        ],
        [
            "Quality class separation",
            weak_separation_result,
            "Most single numeric features show weak class separation",
        ],
        [
            "Quick RF predictability",
            model_result,
            _wrap_text(model_interpretation, width=52),
        ],
        [
            "Timing / identifier leakage",
            f"{leakage_count} columns flagged",
            "Requires scenario-specific feature selection",
        ],
    ]

    fig, ax = plt.subplots(figsize=(15, 7.2))
    ax.axis("off")

    ax.text(
        0,
        1.08,
        "Dataset Realism and Challenge Audit",
        fontsize=16,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    ax.text(
        0,
        1.0,
        (
            "The Level 3 challenge layer tested whether the clean dataset also "
            "preserves expected LPBF physics and predictive structure."
        ),
        fontsize=10,
        ha="left",
        transform=ax.transAxes,
    )

    table = ax.table(
        cellText=rows,
        colLabels=["Challenge area", "Observed result", "Engineering interpretation"],
        colWidths=[0.28, 0.28, 0.44],
        loc="center",
        cellLoc="left",
        colLoc="left",
    )

    table.auto_set_font_size(False)
    table.set_fontsize(7.6)
    table.scale(1, 1.75)

    for key, cell in table.get_celld().items():
        cell.set_edgecolor("black")
        if key[0] == 0:
            cell.set_text_props(weight="bold")

    ax.text(
        0,
        -0.10,
        (
            "Conclusion: the dataset is technically clean and useful for a "
            "production-ML proof of concept, but it should not be presented as "
            "physically validated LPBF production data without further validation."
        ),
        fontsize=10,
        fontweight="bold",
        ha="left",
        transform=ax.transAxes,
    )

    _save_plot(output_dir / "09_dataset_realism_challenge.png")

def _clear_existing_pngs(output_dir: Path) -> None:
    """
    Business objective
    ------------------
    Prevent old, low-priority figures from remaining in the main presentation
    folder after the business plot selection is tightened.

    Coding objective
    ----------------
    Delete only PNG files directly inside the selected output directory. This
    does not delete appendix figures or nested folders.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    for path in output_dir.glob("*.png"):
        path.unlink()


def run_business_plots(
    df: pd.DataFrame,
    eda_output_dir: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR,
) -> None:
    """
    Business objective
    ------------------
    Produce the main Task 1 visual story without overwhelming the reviewer.

    The main story focuses on:
    - dataset scope
    - target balance
    - production data quality
    - distribution realism
    - outlier behavior
    - physics consistency
    - predictive signal
    - prediction timing and leakage
    - production risk

    Coding objective
    ----------------
    Generate only high-value presentation plots in a concise order. Supporting
    plots remain available through run_appendix_business_plots().
    """

    eda_output_dir = Path(eda_output_dir)
    output_dir = Path(output_dir)

    _clear_existing_pngs(output_dir)

    # 01-03: scope, target, and mandatory quality checks.
    plot_dataset_overview(df, output_dir)
    plot_quality_class_distribution(df, output_dir)
    plot_data_quality_audit(eda_output_dir, output_dir)

    # 04-08: data realism and LPBF physics evidence.
    plot_feature_distributions_physics(df, output_dir)
    plot_outlier_assessment(eda_output_dir, output_dir)
    plot_physics_correlation_heatmap(df, output_dir)
    plot_process_window_power_speed(df, output_dir)
    plot_energy_density_quality_physics(df, output_dir)

    # 09: independent challenge layer; this is the key senior-engineering slide.
    plot_physics_consistency_challenge(df, eda_output_dir, output_dir)

    # 10: feature signal and leakage-aware feature interpretation.
    plot_top_mutual_information_features(
        eda_output_dir / "mutual_information.csv",
        output_dir,
    )

    # 11-12: production framing.
    plot_prediction_timing_timeline(output_dir)
    plot_prediction_scenarios_table(output_dir)

    # 13: operational risks and mitigations.
    plot_risk_assessment_details(
        eda_output_dir / "production_risk_assessment.csv",
        output_dir,
    )


def run_appendix_business_plots(
    df: pd.DataFrame,
    eda_output_dir: str | Path,
    output_dir: str | Path = BUSINESS_FIGURES_DIR / "appendix",
) -> None:
    """
    Business objective
    ------------------
    Generate supporting appendix plots for deeper technical review.

    These figures are useful if the interviewer asks for more detail, but they
    are intentionally excluded from the main Task 1 story to keep the main deck
    focused and concise.

    Coding objective
    ----------------
    Write lower-priority supporting figures to reports/figures/business/appendix.
    """

    eda_output_dir = Path(eda_output_dir)
    output_dir = Path(output_dir)

    _clear_existing_pngs(output_dir)

    plot_physics_relationship_assumptions(output_dir)
    plot_process_relationships_by_quality(df, output_dir)
    plot_actionable_categorical_summary(df, output_dir)
    plot_timing_sensitive_features_table(output_dir)
    plot_preprocessing_strategy(output_dir)
    plot_feature_engineering_strategy(output_dir)
    plot_model_decision_tree_strategy(output_dir)
    plot_dataset_assumptions(output_dir)
